### PR TITLE
Adding Linear, Conv, ResNet18, MNIST, and BERT models with TorchDynamo

### PR DESCRIPTION
**Pull request by nhasabni**
1. Adding TorchDynamo based models for Linear, Conv, ResNet18
2. Updating torch_mlir_compile to support TorchDynamo backend generation
3. Fixing issue in generate.sh with changed paths

### CODE REVIEW

**Comment by rengolin** [comment]
I moved the `torch-mlir` directory to `torch-script` so that you could create a `torch-dynamo`, but if you want to have both on the same "front-end", then perhaps we should rename it to just `pytorch`?

**Comment by nhasabni** [comment]
> I moved the `torch-mlir` directory to `torch-script` so that you could create a `torch-dynamo`, but if you want to have both on the same "front-end", then perhaps we should rename it to just `pytorch`?

Hmm, I was thinking of creating `torch-dynamo` as a frontend also. But then I realized that they would share the `torch_compile` code in `lib`. 

So I will create following structure:

`pytorch`
     `|`
     `| - lib` - common py code
     `| - torch-script`
     `| - torch-dynamo`
     `| -` common scripts (generate.sh etc)

Sounds good?

**Comment by rengolin** [comment]
> Sounds good?

Yup

**Review by rengolin — APPROVED** [review]

**Review by rengolin — APPROVED** [review]

**Comment by nhasabni** [comment]
Thanks

**Pull request merged**
